//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliacao()
        {
            this.NotaAluno = new HashSet<NotaAluno>();
        }
    
        public int AvaliacaoId { get; set; }
        public int PessoaId { get; set; }
        public int DataAvaliacaoId { get; set; }
        public string Observacao { get; set; }
        public Nullable<decimal> NotaMaxima { get; set; }
        public string Descricao { get; set; }
        public int StatusId { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaAluno> NotaAluno { get; set; }
    }
}
