//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.DisciplinaCurso = new HashSet<DisciplinaCurso>();
        }
    
        public int CursoId { get; set; }
        public string Descricao { get; set; }
        public int GrauId { get; set; }
        public int Duracao { get; set; }
        public int PessoaId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Grau Grau { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisciplinaCurso> DisciplinaCurso { get; set; }
    }
}
