//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplinaCurso
    {
        public int DisciplinaId { get; set; }
        public int CursoId { get; set; }
        public System.DateTime Data { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Periodo { get; set; }
        public decimal Valor { get; set; }
        public string Turno { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Disciplina Disciplina { get; set; }
    }
}
