//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int EnderecoId { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Complemento { get; set; }
        public int CidadeId { get; set; }
        public string CEP { get; set; }
        public int PessoaId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Status Status { get; set; }
    }
}
