//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Falta
    {
        public int faltaId { get; set; }
        public int AulaId { get; set; }
        public int PessoaId { get; set; }
        public bool Falta1 { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
