//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaAluno
    {
        public int PessoaId { get; set; }
        public int AvaliacaoId { get; set; }
        public decimal Nota { get; set; }
        public string Observacao { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
