//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaDisciplina
    {
        public int DisciplinaId { get; set; }
        public int PessoaId { get; set; }
        public int Ano { get; set; }
        public int Semestre { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataConclusao { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Status Status { get; set; }
    }
}
